// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/echoservice.proto

/*
Package echoservice is a generated protocol buffer package.

It is generated from these files:
	pb/echoservice.proto

It has these top-level messages:
	AppMessage
	AppResponse
	EchoMessage
	EchoResponse
*/
package echoservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppMessage struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *AppMessage) Reset()                    { *m = AppMessage{} }
func (m *AppMessage) String() string            { return proto.CompactTextString(m) }
func (*AppMessage) ProtoMessage()               {}
func (*AppMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AppResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *AppResponse) Reset()                    { *m = AppResponse{} }
func (m *AppResponse) String() string            { return proto.CompactTextString(m) }
func (*AppResponse) ProtoMessage()               {}
func (*AppResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EchoMessage struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *EchoMessage) Reset()                    { *m = EchoMessage{} }
func (m *EchoMessage) String() string            { return proto.CompactTextString(m) }
func (*EchoMessage) ProtoMessage()               {}
func (*EchoMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EchoMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EchoResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EchoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AppMessage)(nil), "echoservice.AppMessage")
	proto.RegisterType((*AppResponse)(nil), "echoservice.AppResponse")
	proto.RegisterType((*EchoMessage)(nil), "echoservice.EchoMessage")
	proto.RegisterType((*EchoResponse)(nil), "echoservice.EchoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EchoService service

type EchoServiceClient interface {
	Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoResponse, error)
}

type echoServiceClient struct {
	cc *grpc.ClientConn
}

func NewEchoServiceClient(cc *grpc.ClientConn) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/echoservice.EchoService/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EchoService service

type EchoServiceServer interface {
	Echo(context.Context, *EchoMessage) (*EchoResponse, error)
}

func RegisterEchoServiceServer(s *grpc.Server, srv EchoServiceServer) {
	s.RegisterService(&_EchoService_serviceDesc, srv)
}

func _EchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echoservice.EchoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo(ctx, req.(*EchoMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _EchoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echoservice.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/echoservice.proto",
}

// Client API for UserServiceApp service

type UserServiceAppClient interface {
	Message(ctx context.Context, in *AppMessage, opts ...grpc.CallOption) (*AppResponse, error)
}

type userServiceAppClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceAppClient(cc *grpc.ClientConn) UserServiceAppClient {
	return &userServiceAppClient{cc}
}

func (c *userServiceAppClient) Message(ctx context.Context, in *AppMessage, opts ...grpc.CallOption) (*AppResponse, error) {
	out := new(AppResponse)
	err := grpc.Invoke(ctx, "/echoservice.UserServiceApp/Message", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserServiceApp service

type UserServiceAppServer interface {
	Message(context.Context, *AppMessage) (*AppResponse, error)
}

func RegisterUserServiceAppServer(s *grpc.Server, srv UserServiceAppServer) {
	s.RegisterService(&_UserServiceApp_serviceDesc, srv)
}

func _UserServiceApp_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceAppServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echoservice.UserServiceApp/Message",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceAppServer).Message(ctx, req.(*AppMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserServiceApp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echoservice.UserServiceApp",
	HandlerType: (*UserServiceAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Message",
			Handler:    _UserServiceApp_Message_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/echoservice.proto",
}

func init() { proto.RegisterFile("pb/echoservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x48, 0xd2, 0x4f,
	0x4d, 0xce, 0xc8, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x46, 0x12, 0x92, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8,
	0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28, 0x55, 0x52,
	0xe3, 0xe2, 0x72, 0x2c, 0x28, 0xf0, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x92, 0xe0, 0x62,
	0xcf, 0x85, 0x30, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x75, 0x2e, 0x6e,
	0xc7, 0x82, 0x82, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0x62, 0x02, 0x0a, 0x5d, 0x93, 0x33, 0xf2,
	0x09, 0x9b, 0xa8, 0xc1, 0xc5, 0x03, 0x52, 0x48, 0xd8, 0x48, 0xa3, 0x14, 0x88, 0x91, 0xc1, 0x10,
	0x0f, 0x09, 0x85, 0x72, 0xb1, 0x80, 0xb8, 0x42, 0x12, 0x7a, 0xc8, 0x3e, 0x47, 0xb2, 0x54, 0x4a,
	0x12, 0x43, 0x06, 0x66, 0x8b, 0x92, 0x44, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0x84, 0x94, 0x78, 0xf5,
	0xcb, 0x0c, 0xc1, 0x21, 0x07, 0x26, 0xac, 0x18, 0xb5, 0x8c, 0x32, 0xb8, 0xf8, 0x42, 0x8b, 0x53,
	0x8b, 0xa0, 0xb6, 0x38, 0x16, 0x14, 0x08, 0x85, 0x71, 0xb1, 0xc3, 0xbc, 0x21, 0x8e, 0x62, 0x22,
	0x22, 0xc4, 0xa4, 0x24, 0xd0, 0x25, 0xb0, 0xdb, 0x54, 0x5a, 0x9c, 0x5a, 0x04, 0xb3, 0xc9, 0x89,
	0x37, 0x0a, 0x39, 0x82, 0x92, 0xd8, 0xc0, 0x31, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x77,
	0x05, 0x5b, 0x70, 0xcc, 0x01, 0x00, 0x00,
}
