// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/userservice.proto

/*
Package userserviceapp is a generated protocol buffer package.

It is generated from these files:
	pb/userservice.proto

It has these top-level messages:
	AppMessage
	AppResponse
*/
package userserviceapp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppMessage struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *AppMessage) Reset()                    { *m = AppMessage{} }
func (m *AppMessage) String() string            { return proto.CompactTextString(m) }
func (*AppMessage) ProtoMessage()               {}
func (*AppMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AppResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *AppResponse) Reset()                    { *m = AppResponse{} }
func (m *AppResponse) String() string            { return proto.CompactTextString(m) }
func (*AppResponse) ProtoMessage()               {}
func (*AppResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AppMessage)(nil), "userserviceapp.AppMessage")
	proto.RegisterType((*AppResponse)(nil), "userserviceapp.AppResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserServiceApp service

type UserServiceAppClient interface {
	Message(ctx context.Context, in *AppMessage, opts ...grpc.CallOption) (*AppResponse, error)
}

type userServiceAppClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceAppClient(cc *grpc.ClientConn) UserServiceAppClient {
	return &userServiceAppClient{cc}
}

func (c *userServiceAppClient) Message(ctx context.Context, in *AppMessage, opts ...grpc.CallOption) (*AppResponse, error) {
	out := new(AppResponse)
	err := grpc.Invoke(ctx, "/userserviceapp.UserServiceApp/Message", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserServiceApp service

type UserServiceAppServer interface {
	Message(context.Context, *AppMessage) (*AppResponse, error)
}

func RegisterUserServiceAppServer(s *grpc.Server, srv UserServiceAppServer) {
	s.RegisterService(&_UserServiceApp_serviceDesc, srv)
}

func _UserServiceApp_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceAppServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userserviceapp.UserServiceApp/Message",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceAppServer).Message(ctx, req.(*AppMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserServiceApp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userserviceapp.UserServiceApp",
	HandlerType: (*UserServiceAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Message",
			Handler:    _UserServiceApp_Message_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/userservice.proto",
}

func init() { proto.RegisterFile("pb/userservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x48, 0xd2, 0x2f,
	0x2d, 0x4e, 0x2d, 0x2a, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x43, 0x12, 0x4a, 0x2c, 0x28, 0x90, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5,
	0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86,
	0xa8, 0x56, 0x52, 0xe3, 0xe2, 0x72, 0x2c, 0x28, 0xf0, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15,
	0x92, 0xe0, 0x62, 0xcf, 0x85, 0x30, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25,
	0x75, 0x2e, 0x6e, 0xc7, 0x82, 0x82, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0x62, 0x3c, 0x0a, 0x8d,
	0x0a, 0xb9, 0xf8, 0x42, 0x8b, 0x53, 0x8b, 0x82, 0x21, 0x0e, 0x70, 0x2c, 0x28, 0x10, 0x8a, 0xe7,
	0x62, 0x87, 0x99, 0x2f, 0xa5, 0x87, 0xea, 0x38, 0x3d, 0x84, 0xdd, 0x52, 0xd2, 0x58, 0xe4, 0x60,
	0xf6, 0x29, 0x49, 0x37, 0x5d, 0x7e, 0x32, 0x99, 0x49, 0x54, 0x49, 0x40, 0xbf, 0xcc, 0x10, 0xec,
	0xe7, 0xc4, 0x82, 0x02, 0xfd, 0xd4, 0xe4, 0x8c, 0x7c, 0x2b, 0x46, 0x2d, 0x27, 0x81, 0x28, 0x34,
	0x3f, 0x27, 0xb1, 0x81, 0x3d, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x47, 0xeb, 0x69, 0x28,
	0x22, 0x01, 0x00, 0x00,
}
